### ISSUE TITLE
No region name for other language

### ISSUE THREAD

**Issue by Value2299** [seriaati/ambr#5]
the region value is INAZUMA for example, how can I get the region locale name? By the way, what's the code for region icon?

**Comment by seriaati** [comment]
Region locale names are currently not provided by the ambr API, but I've just asked their devs if it's possible to add them.
For region icons, you can find them on the Genshin Impact wiki, like [HERE](https://genshin-impact.fandom.com/wiki/Inazuma)

**Comment by Value2299** [comment]
> Region locale names are currently not provided by the ambr API, but I've just asked their devs if it's possible to add them.
> For region icons, you can find them on the Genshin Impact wiki, like [HERE](https://genshin-impact.fandom.com/wiki/Inazuma)

yeah, I know I can find everything there, but I want my app to fetch icons through API automatically.
Anyway, thank you so much for contacting the devs.

**Comment by seriaati** [comment]
If the API hosts the icons then I'd add them, but currently I don't see them anywhere on the site
